"""Build the Traxler native real-label validation fold for the self-improvement loop.

Reads the offline pseudobulk (``{pert: {gene: log2fc}}``, Traxler untreated
macrophages) and thresholds it into challenge-schema labels via
``bio_reasoning.data.traxler_labels``. Both the input json and the output csv live
under gitignored ``data/external/`` — the csv is a reproducible artifact (like
``train.csv``), regenerated by this script rather than committed.

Usage:
    uv run python scripts/build_traxler_labels.py                 # default threshold 1.0
    uv run python scripts/build_traxler_labels.py --threshold 0.5
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from bio_reasoning.data.traxler_labels import (
    DEFAULT_THRESHOLD,
    label_distribution,
    logfc_to_labels,
)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_IN = ROOT / "data" / "external" / "traxler_native_lookup.json"
DEFAULT_OUT = ROOT / "data" / "external" / "traxler_labels.csv"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--in-json", type=Path, default=DEFAULT_IN, help="Pseudobulk log2FC lookup.")
    ap.add_argument("--out-csv", type=Path, default=DEFAULT_OUT)
    ap.add_argument(
        "--threshold", type=float, default=DEFAULT_THRESHOLD, help="|log2FC| DE cutoff."
    )
    args = ap.parse_args()

    if not args.in_json.exists():
        raise SystemExit(
            f"missing pseudobulk input: {args.in_json}\n"
            "The Traxler pseudobulk is computed offline; place the lookup json here first."
        )
    lookup = json.loads(args.in_json.read_text())
    df = logfc_to_labels(lookup, threshold=args.threshold)
    args.out_csv.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(args.out_csv, index=False)

    d = label_distribution(df)
    de_pct = 100 * d["de"] / d["n_pairs"] if d["n_pairs"] else 0.0
    print(
        f"[traxler] threshold=|log2FC|>={args.threshold}  perts={d['n_perts']}  "
        f"pairs={d['n_pairs']}  DE={d['de']} ({de_pct:.2f}%)  up={d['up']} down={d['down']} "
        f"none={d['none']}\n[traxler] wrote {args.out_csv}"
    )
    if d["de"] == 0:
        print("[traxler] WARNING: all labels are 'none' — lower the threshold; fold is unusable.")


if __name__ == "__main__":
    main()
